(function(){
    window.IBQuestions = [
		"If you could speak to anyone in heaven, who would it be?",
		"What memory do you replay the most in your mind?",
		"How important is physical attraction to you?",
		"Do you have any reoccurring dreams or nightmares?",
		"At what age did you learn the most about yourself?",
		"When was the last time you were disappointed in yourself?",
		"Is there someone that you’ll never forgive?",
		"Do you think your parents are proud of where you are in life?",
		"What’s the worst physical pain that you’ve ever suffered through?",
		"What’s the most intimate thing a couple could do together?",
		"Do you believe in ghosts, aliens, or any mythical creatures?",
		"When do you feel the most attractive?",
		"What unanswerable question bothers you the most?",
		"At what age did you start to consider yourself an adult?",
		"What is the meanest thing your inner voice tells you?",
		"Were you ever tempted to cheat on a past partner?",
		"What do you do when you’re feeling lonely?",
		"What type of animal would you like to be reincarnated as?",
		"Do you believe every life has an equal value?",
		"Do you sleep in pajamas, lingerie or naked?",
		"Do you daydream more about the future or your past?",
		"What would instantly make you fall out of love with someone?",
		"Have you ever been in love before?",
		"Do you believe you’re going to be a good parent?",
		"What scares you the most about growing old?",
		"Do you like the sound of your name?",
		"How long did it take you to learn to love yourself?",
		"Have you ever manipulated someone to get what you wanted?",
		"Do you believe in love at first sight or do you think it takes time to grow?",
		"Do you believe in destiny?",
		"Do you feel like anything is missing from your life?",
		"What thoughts make you unhappy?",
		"What’s the most childish thing you still love to do?",
		"Do you believe success comes in the form of money or happiness?",
		"Before making a telephone call, do you ever rehearse what you are going to say? Why?",
		"What would constitute a “perfect” day for you?",
		"When did you last sing to yourself? To someone else?",
		"Do you have a secret hunch about how you will die?",
		"Name three things you and your game partner appear to have in common.",
		"For what in your life do you feel most grateful?",
		"If you could change anything about the way you were raised, what would it be?",
		"What would you change about yourself?",
		"Take four minutes and tell your gaming-partner your life story in as much detail as possible.",
		"If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?",
		"What is the greatest accomplishment of your life?",
		"What do you value most in a friendship?",
		"What is your most treasured memory?",
		"What is your most terrible memory?",
		"What is the first thing you noticed about your partner",
		"What role does physical attraction play in whether or not you pursue a relationship?",
		"If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?",
		"What does friendship mean to you?",
		"What roles do love and affection play in your life?",
		"Alternate sharing something you consider a positive characteristic of your gaming partner. Share a total of 3 items.",
		"How close and warm is your family? Do you feel your childhood was happier than most other people’s?",
		"How do you feel about your relationship with your mother?",
		"Make three true “we” statements each. For instance, “We are both in this room feeling ... ",
		"Complete this sentence: “I wish I had someone with whom I could share ... ",
		"If you could have three wishes from your game partner, what would they be?",
		"If you were going to become a close friend with your Game partner, please share what would be important for him or her to know.",
		"Tell your partner what you like about them; be very honest this time, saying things that you might not say to someone you’ve just met.",
		"Share with your partner an embarrassing moment in your life.",
		"When did you last cry in front of another person? By yourself?",
		"What, if anything, is too serious to be joked about?",
		"Your house, containing everything you own, catches fire. After saving your loved ones and pets, you have time to safely make a final dash to save any one item. What would it be? Why?",
		"Of all the people in your family, whose death would you find most disturbing? Why?",
		"How do you feel about the merits of pornograph",
		"What’s the dirtiest thought you’ve ever had about a total stranger?",
		"What’s the dirtiest fantasy you’ve had at work?",
		"What do you do when you get horny in public?",
		"Do you remember what that first orgasm felt like?",
		"Have you ever had sex with someone whose name you never knew?",
		"Have you ever kissed someone of the same sex?",  
		"How would you respond if a couple approached you to be their “third”?",
		"What types of compliments do you like to hear?",
		"Is there anything you won’t do in bed?",
		"How old were you when you lost your virginity?",
		"Would you rather die a virgin or a whore?",
		"Would you rather: Have amazing sex that lasts 47 seconds? Or have average sex that lasts 10 minutes?",
		"If u had a Deathnote, would you use it?",
    ];
})();
